### ISSUE TITLE
Baby zombies spawning/crafting table properties

### ISSUE THREAD

**Issue by sleepyzer0** [spzi/ClassicPack-Base-IssueTracker#3]
Hello. I removed the cascade pack and rendered a beta world with everything seeming to work (except for some reason in latest version I can break the crafting table faster with an axe). I love this modpack so much but also for some reason I can't seem to find what or why baby zombies spawn! I couldn't find anything in the JSON files to modify for this. Unsure if bug or mistake by me but everything else is working wonderful!

**Comment by spzi** [comment]
Modern breaking speeds are intentional as a quality of life feature, I have tried to remove baby zombies but it's a much more difficult task as they aren't a separate mob and instead are a regular zombie with a modifier, I'll likely figure it out eventually
